version: "3.3"

services:
  my_backend:
    platform: linux/amd64
    image: asia.gcr.io/resolute-world-344710/my_backend:1.8
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .env:/my_backend/.env
